config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "/" => "users#index"
  get "/login" => "users#login"
  get "/register" => "users#register"
  post '/sessions' => 'sessions#create'
  post "/users" => 'users#create'
  get "/dashboard" => 'tests#index'
  delete "/logout" => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def create
    user = User.find_by(email:login_params[:email])
    puts ">>>>>>>>>>>>>>",user.name
    if user && user.authenticate(login_params[:password])
        session[:user_id] = user.id 
        redirect_to '/dashboard' 
    else
      flash[:login_errors] = ['invalid credentials']
      redirect_to '/'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private
  def login_params
    params.require(:login).permit(:email,:password);
  end


end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @user = User.find(session[:user_id]) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
     @user = User.new(user_params)
   
     if user.save
      session[:user_id] = user.id 
      redirect_to '/dashboard'
     else
      flash[:register_errors] = user.errors.full_messages
      redirect_to '/'
     end
  end

  private

  def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>login and registration</title>
</head>
<body>
<%= button_to "Login", login_path,method: :get %>
<%= button_to "register", register_path,method: :get %>

</body>
</html>

app/views/users/login.html.erb
<!DOCTYPE html>
<html>
<head>
<title>login</title>
</head>
<body>
<h1>Login</h1>

<form action="/sessions" method="POST">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
 <input type="email" name="login[email]" placeholder="email">
 <input type="password" name="login[password]" placeholder="password">
 <input type="submit" name="submit" class="submit">
</form>


</body>
</html>

app/views/users/register.html.erb
<!DOCTYPE html>
<html>
<head>
<title>registration</title>
</head>
<body>

<h1>Register</h1>

<form action ="/users" method="POST">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<input type="name" name="user[name]" placeholder="name">
<input type="email" name="user[email]" placeholder="enail">
<input type="password" name="user[password]" placeholder="password">
<input type="password" name="user[password_confirmation]" placeholder="password_confirmation">
<input type="submit" name="submit" class="submit">
</form>
</body>
</html>